spring.datasource.url=jdbc:mysql://127.0.0.1:3306/ctrlf?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Awesomeness1!
# Always run sample-data.sql to initialize SQL when app starts
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:sample-data.sql